events/config/routes.rb
Rails.application.routes.draw do
    root "events#index"
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   # get "events" => "events#index"
   # get "events/:id" => "events#show", as: "event"
   # get "events/:id/edit" => "events#edit", as: "edit_event"
   # patch "events/:id" => "events#update"
    resources :events
end

events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

events/app/models/event.rb
class Event < ApplicationRecord
  def free?
    price.blank? || price.zero?
  end
end

events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
  def show
    @event = Event.find(params[:id])
  end
  def edit
    @event = Event.find(params[:id])
  end
  def update
    @event = Event.find(params[:id])
    event_params = params.require(:event).
    permit(:title, :description, :location, :price, :starts_at)
    @event.update(event_params)
    redirect_to @event
  end
  def new
    @event = Event.new
  end
  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to @event
  end
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end
    
end

private

  def event_params
    params.require(:event).
      permit(:title, :description, :location, :price, :starts_at)
  end
  

events/app/helpers/application_helper.rb
module ApplicationHelper
end

events/app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
     content_tag(:strong, "Free!")
    else
     number_to_currency(event.price)
    end
  end
end

events/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title, autofocus: true %>
</p>
<p>
  <%= f.label :description %><br/>
  <%= f.text_area :description, cols:40, rows:7 %>
</p>
<p>
  <%= f.label :location %><br/>
  <%= f.text_field :location %>
</p>
<p>
  <%= f.label :price %><br/>
  <%= f.number_field :price, default: 0 %>
</p>
<p>
  <%= f.label :starts_at %><br/>
  <%= f.datetime_select :starts_at %>
</p>

<p>
  <%= f.submit %>
  <% link_to "Cancel", events_path %>
</p>

<% end %>

events/app/views/events/edit.html.erb
<h1>Editing <%= @event.title %> </h1>

<%= render 'form' %>

events/app/views/events/index.html.erb
<h1><%= pluralize(@events.size, "Event") %></h1>

<%= link_to "Create New Event", new_event_path %>
  <% @events.each do |event| %>
  <article>
    <header>
    <h2><%= link_to(event.title, event) %></h2>
    </header>
    <p>
      <%= truncate(event.description, length: 25, separator:' ') %>
    </p>
    <table>
      <tr>
        <th>When:</th>
        <td><%= event.starts_at %></td>
      </tr>
      <tr>
        <th>Where:</th>
        <td><%= event.location %></td>
        </tr>
      </tr>
      <tr>
        <th>Price:</th>
        <td><%= format_price(event) %></td>
      </tr>
    </table>
  </article>
<% end %>

events/app/views/events/new.html.erb
<h1>Create New Event</h1>

<%= render 'form' %>

events/app/views/events/show.html.erb
  <article>
    <header>
    <h2><%= @event.title %></h2>
    </header>
    <p>
      <%= @event.description %>
    </p>
    <table>
      <tr>
        <th>When:</th>
        <td><%= @event.starts_at %></td>
      </tr>
      <tr>
        <th>Where:</th>
        <td><%= @event.location %></td>
        </tr>
      </tr>
      <tr>
        <th>Price:</th>
        <td><%= format_price(@event) %></td>
      </tr>
    </table>
  </article>
  
  <%= link_to "All Events", root_path %> |
  <%= link_to "Edit", edit_event_path(@event) %> |
  <%= link_to "Delete", event_path(@event), method: :delete, data: {confirm: 'Are you sure?'} %>

events/app/views/layouts/_footer.html.erb
<footer id="page-footer">
      <p style="text-align: center;">
        Copyright &copy; 2018
      </p>
  </footer>

events/app/views/layouts/_header.html.erb
<header id="page-header">
      <div>
      <h1 <%= link_to "Event Tracking App", root_path %></h1>
      </div>
</header>

events/app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
    <div id="search-bar" style="field-align: center;">
        <%= form_tag  search_customers_path do %>
        <input class="search full-width" id="searchbar" name="query" placeholder= "Search for Events" type= "text" autocomplete="off">
        <% end %>
    </div>
    <nav>
        <ul>
            <li class="all-events">
            <%= link_to 'All Events', root_path, class: 'button' %>
          </li>
          <li class="create-event">
            <%= link_to 'Add New Event', new_event_path, class: 'button' %>
        </ul>
         </li>
     </nav>
</aside>

events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>



<%= render "layouts/header" %>

<%= render "layouts/sidebar" %>
  
  <body>
    <%= yield %>
  </body>
  
<%= render "layouts/footer" %>
</html>