cars/config/routes.rb
Rails.application.routes.draw do
  root "vehicles#index"
  post "vehicles/search" => "vehicles#search", as: "search_vehicles"
  resources :vehicles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cars/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cars/app/models/vehicle.rb
class Vehicle < ApplicationRecord
 # def low_miles?
 #   miles < 5000
 # end
  def title
    "#{self.year} #{self.make} #{self.model}"   
  end
  def days_on_lot
    start_date = self.on_lot_at
    end_date = Time.current
    ((end_date - start_date).to_f / 1.day).floor
  end
end

cars/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

cars/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    @vehicles = Vehicle.all
  end
  def show
    @vehicle = Vehicle.find(params[:id])
  end
  def edit
    @vehicle = Vehicle.find(params[:id])
  end
  def new
    @vehicle = Vehicle.new
  end
  def update
    @vehicle = Vehicle.find(params[:id])
    @vehicle.update(vehicle_params)
    redirect_to @vehicle
  end
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.save
    redirect_to @vehicle
  end
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    redirect_to vehicles_url
  end
  def search
    @q = "%#{params[:query]}%"
    @vehicles = Vehicle.where("make LIKE ? or model LIKE ? or year LIKE ? or trim_level LIKE ?", @q, @q, @q, @q)
    render 'index'
  end
  
  private_methods
  def vehicle_params
    params.require(:vehicle).
      permit(:make, :model, :year, :miles, :vin, :body_description, :body_style, :body_door_count, :city_mpg, :highway_mpg, :classification, :drive_train_description, :drive_train_type, :drive_train_wheel_count, :drive_train_front_rear, :engine_description, :engine_displacement, :engine_displacement_unit, :engine_block_style, :engine_cylinder_count, :engine_valve_count, :engine_fuel_type, :engine_fuel_intake, :engine_camshaft, :exterior_color, :exterior_base_color, :exterior_color_code, :exterior_color_finish, :trim_level, :price, :on_lot_at, :status, :interior_color, :interior_fabric, :model_type, :new_or_used, :features)
  end
end

cars/app/helpers/application_helper.rb
module ApplicationHelper
end

cars/app/helpers/vehicles_helper.rb
module VehiclesHelper
  def format_price(vehicle)
    number_to_currency(vehicle.price)
  end
 # def format_miles(vehicle)
 #   if vehicle.low_miles?
 #     content_tag(:Strong, "Low Miles!")
 #   else
  #    vehicle.miles
 #   end
 # end
end

cars/app/views/layouts/_footer.html.erb
<footer id="page-footer">
      <p style="text-align: center;">
        Copyright &copy; 2018
      </p>
  </footer>

cars/app/views/layouts/_header.html.erb
<header id="page-header">
      <div>
      <h1 <%= link_to "Dealership Inventory Software", root_path %></h1>
      </div>
</header>

cars/app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
    <div id="search-bar" style="field-align: center;">
        <%= form_tag  search_vehicles_path do %>
        <input class="search full-width" id="searchbar" name="query" placeholder= "Search for Vehicles" type= "text" autocomplete="off">
        <% end %>
    </div>
    <nav>
        <ul>
            <li>
                <%= link_to 'All Vehicles', root_path, class: 'button' %>
            </li>
            <li>
                <%= link_to 'Add New Vehicle', new_vehicle_path, class: 'button' %>
            </li>
        </ul>
    </nav>
</aside>

cars/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DealershipX Vehicle Inventory</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>



<%= render "layouts/header" %>

<%= render "layouts/sidebar" %>
  
  <body>
    <%= yield %>
  </body>
  
<%= render "layouts/footer" %>
</html>

cars/app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <p>
    <%= f.label :year %><br/>
    <%= f.number_field :year, default: 2018%>
  </p>
  <p>
    <%= f.label :make %><br/>
    <%= f.text_field :make, autofocus: true%>
  </p>
  <p>
    <%= f.label :model %><br/>
    <%= f.text_field :model %>
  </p>
  <p>
    <%= f.label :price %><br/>
    <%= f.number_field :price, default: 0 %>
  </p>
  <p>
    <%= f.label :miles %><br/>
    <%= f.number_field :miles %>
  </p>
  <p>
    <%= f.label :date_arrived_on_lot %><br/>
    <%= f.datetime_select :on_lot_at %>
  </p>
  <p>
    <%= f.label :vin %><br/>
    <%= f.text_field :vin %>
  </p>
  <p>
    <%= f.label :body_description %><br/>
    <%= f.text_field :body_description%>
  </p>
  <p>
    <%= f.label :body_style %><br/>
    <%= f.text_field :body_style %>
  </p>
  <p>
    <%= f.label :body_door_count %><br/>
    <%= f.number_field :body_door_count %>
  </p>
  <p>
    <%= f.label :city_mpg %><br/>
    <%= f.number_field :city_mpg %>
  </p>
  <p>
    <%= f.label :highway_mpg %><br/>
    <%= f.number_field :highway_mpg %>
  </p>
  <p>
    <%= f.label :classification %><br/>
    <%= f.text_field :classification %>
  </p>
  <p>
    <%= f.label :drive_train_description %><br/>
    <%= f.text_field :drive_train_description %>
  </p>
  <p>
    <%= f.label :drive_train_type %><br/>
    <%= f.number_field :drive_train_type %>
  </p>
  <p>
    <%= f.label :drive_train_wheel_count %><br/>
    <%= f.number_field :drive_train_wheel_count %>
  </p>
  <p>
    <%= f.label :drive_train_front_or_rear %><br/>
    <%= f.text_field :drive_train_front_rear %>
  </p>
  <p>
    <%= f.label :engine_description %><br/>
    <%= f.text_field :engine_description %>
  </p>
  <p>
    <%= f.label :engine_displacement %><br/>
    <%= f.number_field :engine_displacement %>
  </p>
  <p>
    <%= f.label :engine_displacement_unit %><br/>
    <%= f.text_field :engine_displacement_unit %>
  </p>
  <p>
    <%= f.label :engine_block_style %><br/>
    <%= f.text_field :engine_block_style %>
  </p>
  <p>
    <%= f.label :engine_cylinder_count %><br/>
    <%= f.number_field :engine_cyclinder_count %>
  </p>
  <p>
    <%= f.label :engine_valve_count %><br/>
    <%= f.number_field :engine_valve_count %>
  </p>
  <p>
    <%= f.label :engine_fuel_type %><br/>
    <%= f.text_field :engine_fuel_type %>
  </p>
  <p>
    <%= f.label :engine_fuel_intake %><br/>
    <%= f.text_field :engine_fuel_intake %>
  </p>
  <p>
    <%= f.label :engine_camshaft %><br/>
    <%= f.text_field :engine_camshaft %>
  </p>
  <p>
    <%= f.label :exterior_color %><br/>
    <%= f.text_field :exterior_color %>
  </p>
  <p>
    <%= f.label :exterior_base_color %><br/>
    <%= f.text_field :exterior_base_color %>
  </p>
  <p>
    <%= f.label :exterior_color_code %><br/>
    <%= f.text_field :exterior_color_code %>
  </p>
  <p>
    <%= f.label :exterior_color_finish %><br/>
    <%= f.text_field :exterior_color_finish %>
  </p>
  <p>
    <%= f.label :trim_level %><br/>
    <%= f.text_field :trim_level %>
  </p>
  <p>
    <%= f.label :status %><br/>
    <%= f.text_field :status %>
  </p>
  <p>
    <%= f.label :interior_color %><br/>
    <%= f.text_field :interior_color %>
  </p>
  <p>
    <%= f.label :interior_fabric %><br/>
    <%= f.text_field :interior_fabric %>
  </p>
  <p>
    <%= f.label :model_type %><br/>
    <%= f.text_field :model_type %>
  </p>
  <p>
    <%= f.label :new_or_used %><br/>
    <%= f.text_field :new_or_used %>
  </p>
  <p>
    <%= f.label :features %><br/>
    <%= f.text_field :features %>
  </p>
  <p>
    <%= f.submit %>
    <% link_to "Cancel", vehicles_path %>
  </p>
<% end %>

cars/app/views/vehicles/edit.html.erb
<h1>Editing: <%= @vehicle.title %></h1>

<%= render  'form' %>


cars/app/views/vehicles/index.html.erb
<h1> <%= pluralize(@vehicles.size, "Vehicle") %> in Inventory</h1>
<ul>
  <% @vehicles.each do |vehicle| %>
    <h3><%= link_to(vehicle.title, vehicle_path(vehicle)) %></h3>
    <li><%= vehicle.miles %></li>
    <li><%= format_price(vehicle) %></li>
    <li> Arrived on lot <%= vehicle.days_on_lot %> days ago</li>
  <% end %>
</ul>


cars/app/views/vehicles/new.html.erb
<h1>Add New Vehicle</h1>

<%= render 'form' %>

cars/app/views/vehicles/show.html.erb
<article>
  <header>
    <h1><%= @vehicle.title %></h1>
  </header>
  <h3>Miles:<h3>
  <p>
    <%= @vehicle.miles %>
  </p>
  <h3>Arrived on Lot:</h3>
  <p>
    <%= @vehicle.days_on_lot %>
  </p>
  <h3>Price:</h3>
  <p>
    <%= format_price(@vehicle) %>
  </p>
  <h3>Vin#:</h3>
  <p>
    <%= @vehicle.vin %>
  </p>
  <h3>Body Description:</h3>
  <p>
    <%= @vehicle.body_description %>
  </p>
  <h3>Body Style:</h3>
  <p>
    <%= @vehicle.body_style %>
  </p>
  <p>
    <%= @vehicle.trim_level %>
  </p>
  <h3>Doors:</h3>
  <p>
    <%= @vehicle.body_door_count %>
  </p>
  <h3>City MPG:</h3>
  <p>
    <%= @vehicle.city_mpg %>
  </p>
  <h3>Highway MPG:</h3>
  <p>
    <%= @vehicle.highway_mpg %>
  </p>
  <h3>Classification:</h3>
  <p>
    <%= @vehicle.classification %>
  </p>
  <h3>Drive Train:</h3>
  <p>
    <%= @vehicle.drive_train_description %>
  </p>
  <p>
    <%= @vehicle.drive_train_type %>
  </p>
  <p>
    <%= @vehicle.drive_train_wheel_count %>
  </p>
  <p>
    <%= @vehicle.drive_train_front_rear %>
  </p>
  <h3>Engine:</h3>
  <p>
    <%= @vehicle.engine_description %>
  </p>
  <p>
    <%= @vehicle.engine_displacement %>
  </p>
  <p>
    <%= @vehicle.engine_displacement_unit %>
  </p>
  <p>
    <%= @vehicle.engine_block_style %>
  </p>
  <p>
    <%= @vehicle.engine_cylinder_count %>
  </p>
  <p>
    <%= @vehicle.engine_valve_count %>
  </p>
  <p>
    <%= @vehicle.engine_fuel_type %>
  </p>
  <p>
    <%= @vehicle.engine_fuel_intake %>
  </p>
  <p>
    <%= @vehicle.engine_camshaft %>
  </p>
  <h3> Exterior:</h3>
  <p>
    <%= @vehicle.exterior_color %>
  </p>
  <p>
    <%= @vehicle.exterior_base_color %>
  </p>
  <p>
    <%= @vehicle.exterior_color_code %>
  </p>
  <p>
    <%= @vehicle.exterior_color_finish %>
  </p>
  <p>
    <%= @vehicle.status %>
  </p>
  <h3>Interior:</h3>
  <p>
    <%= @vehicle.interior_color %>
  </p>
  <p>
    <%= @vehicle.interior_fabric %>
  </p>
  <p>
    <%= @vehicle.model_type %>
  </p>
  <p>
    <%= @vehicle.new_or_used %>
  </p>
  <p>
    <%= @vehicle.features %>
  </p>
</article>


<nav>
<%= link_to "All Movies", root_path %>  |
<%= link_to "Edit", edit_vehicle_path(@vehicle) %> |
<%= link_to "Delete", vehicle_path(@vehicle), method: :delete, data: {confirm: 'Are you sure?'} %>
</nav>